<?php

declare(strict_types=1);

namespace App\Services\DNS;

use App\Core\Exceptions\ValidationException;
use App\Core\Logger;

class BindZoneService
{
    private Logger $logger;

    public function __construct(Logger $logger)
    {
        $this->logger = $logger;
    }

    /**
     * Parses a standard BIND zone file content into structured zone and RRsets.
     *
     * @param string $zoneContent
     * @param string|null $fallbackOrigin
     * @return array{origin: string, ttl: int, records: array<int, array{name: string, type: string, ttl: int, content: string}>}
     */
    public function parse(string $zoneContent, ?string $fallbackOrigin = null): array
    {
        $origin = $fallbackOrigin !== null ? rtrim($fallbackOrigin, '.') . '.' : '';
        $currentTtl = 3600;
        $records = [];
        $lastName = $origin;

        // Normalize newlines and strip comments while handling quotes
        $lines = explode("\n", str_replace(["\r\n", "\r"], "\n", $zoneContent));
        $unrolledLines = [];
        $multilineBuffer = '';
        $inMultiline = false;

        foreach ($lines as $line) {
            $cleaned = $this->stripComments($line);
            if (trim($cleaned) === '') {
                continue;
            }

            if (!$inMultiline) {
                if (str_contains($cleaned, '(')) {
                    $inMultiline = true;
                    $multilineBuffer = str_replace('(', ' ', $cleaned);
                    if (str_contains($multilineBuffer, ')')) {
                        $inMultiline = false;
                        $unrolledLines[] = trim(str_replace(')', ' ', $multilineBuffer));
                        $multilineBuffer = '';
                    }
                } else {
                    $unrolledLines[] = trim($cleaned);
                }
            } else {
                if (str_contains($cleaned, ')')) {
                    $inMultiline = false;
                    $multilineBuffer .= ' ' . str_replace(')', ' ', $cleaned);
                    $unrolledLines[] = trim($multilineBuffer);
                    $multilineBuffer = '';
                } else {
                    $multilineBuffer .= ' ' . $cleaned;
                }
            }
        }

        foreach ($unrolledLines as $line) {
            $tokens = preg_split('/\s+/', trim($line));
            if (empty($tokens)) {
                continue;
            }

            $firstToken = strtoupper($tokens[0]);

            // Handle control directives
            if ($firstToken === '$ORIGIN') {
                if (isset($tokens[1])) {
                    $origin = rtrim($tokens[1], '.') . '.';
                    $lastName = $origin;
                }
                continue;
            }

            if ($firstToken === '$TTL') {
                if (isset($tokens[1])) {
                    $currentTtl = $this->parseTtl($tokens[1]);
                }
                continue;
            }

            // Parse RR line
            $record = $this->parseRecordLine($tokens, $origin, $currentTtl, $lastName);
            if ($record !== null) {
                $lastName = $record['name'];
                $records[] = $record;
            }
        }

        if ($origin === '') {
            foreach ($records as $r) {
                if ($r['type'] === 'SOA') {
                    $origin = $r['name'];
                    break;
                }
            }
        }

        if ($origin === '') {
            throw new ValidationException(['zone' => 'Could not determine zone origin from BIND file']);
        }

        $this->logger->info('Successfully parsed BIND zone file', [
            'origin' => $origin,
            'records_count' => count($records),
        ]);

        return [
            'origin' => $origin,
            'ttl' => $currentTtl,
            'records' => $records,
        ];
    }

    /**
     * Serializes zone metadata and records to standard BIND zone format.
     */
    public function serialize(string $zoneName, array $records, int $defaultTtl = 3600): string
    {
        $zoneName = rtrim($zoneName, '.') . '.';
        $output = [];
        $output[] = "; BIND Zone file generated by PHP-PDNSManager Enterprise";
        $output[] = "; Export Date: " . date('r');
        $output[] = "\$ORIGIN {$zoneName}";
        $output[] = "\$TTL {$defaultTtl}";
        $output[] = "";

        // Put SOA and NS records first
        $soa = null;
        $nsList = [];
        $otherList = [];

        foreach ($records as $record) {
            $type = strtoupper((string) ($record['type'] ?? ''));
            if ($type === 'SOA') {
                $soa = $record;
            } elseif ($type === 'NS') {
                $nsList[] = $record;
            } else {
                $otherList[] = $record;
            }
        }

        if ($soa !== null) {
            $output[] = sprintf("%-24s %-6d IN %-6s %s", $soa['name'] ?? '@', $soa['ttl'] ?? $defaultTtl, 'SOA', $soa['content'] ?? '');
        }

        foreach ($nsList as $ns) {
            $output[] = sprintf("%-24s %-6d IN %-6s %s", $ns['name'] ?? '@', $ns['ttl'] ?? $defaultTtl, 'NS', $ns['content'] ?? '');
        }

        if (!empty($nsList)) {
            $output[] = "";
        }

        foreach ($otherList as $rec) {
            $content = (string) ($rec['content'] ?? '');
            $type = strtoupper((string) ($rec['type'] ?? 'A'));
            if ($type === 'TXT' && !str_starts_with($content, '"')) {
                $content = '"' . addcslashes($content, '"\\') . '"';
            }
            $output[] = sprintf("%-24s %-6d IN %-6s %s", $rec['name'] ?? '@', $rec['ttl'] ?? $defaultTtl, $type, $content);
        }

        $output[] = "";
        return implode("\n", $output);
    }

    private function stripComments(string $line): string
    {
        $inQuotes = false;
        $len = strlen($line);
        $result = '';
        for ($i = 0; $i < $len; $i++) {
            $char = $line[$i];
            if ($char === '"' && ($i === 0 || $line[$i - 1] !== '\\')) {
                $inQuotes = !$inQuotes;
            }
            if ($char === ';' && !$inQuotes) {
                break;
            }
            $result .= $char;
        }
        return $result;
    }

    private function parseRecordLine(array $tokens, string $origin, int $defaultTtl, string $lastName): ?array
    {
        $name = $tokens[0];
        $idx = 1;

        if ($name === '@') {
            $name = $origin;
        } elseif (!str_ends_with($name, '.')) {
            // Check if first token is TTL or Class or Type (omitted name)
            if (is_numeric($name) || in_array(strtoupper($name), ['IN', 'CS', 'CH', 'HS', 'A', 'AAAA', 'CNAME', 'MX', 'TXT', 'NS', 'SOA', 'PTR', 'SRV', 'CAA'], true)) {
                $name = $lastName;
                $idx = 0;
            } else {
                $name = $origin !== '' ? $name . '.' . $origin : $name . '.';
            }
        }

        $ttl = $defaultTtl;
        $class = 'IN';

        if (isset($tokens[$idx]) && is_numeric($tokens[$idx])) {
            $ttl = (int) $tokens[$idx];
            $idx++;
        }

        if (isset($tokens[$idx]) && strtoupper($tokens[$idx]) === 'IN') {
            $class = 'IN';
            $idx++;
        }

        if (!isset($tokens[$idx])) {
            return null;
        }

        $type = strtoupper($tokens[$idx]);
        $idx++;

        $contentParts = array_slice($tokens, $idx);
        $content = implode(' ', $contentParts);

        if ($type === 'TXT' && !str_starts_with($content, '"')) {
            $content = '"' . trim($content, '"') . '"';
        }

        return [
            'name' => $name,
            'type' => $type,
            'ttl' => $ttl,
            'content' => $content,
        ];
    }

    private function parseTtl(string $ttlStr): int
    {
        $ttlStr = trim($ttlStr);
        if (is_numeric($ttlStr)) {
            return (int) $ttlStr;
        }

        $unit = strtolower(substr($ttlStr, -1));
        $val = (int) substr($ttlStr, 0, -1);
        return match ($unit) {
            's' => $val,
            'm' => $val * 60,
            'h' => $val * 3600,
            'd' => $val * 86400,
            'w' => $val * 604800,
            default => (int) $ttlStr,
        };
    }
}
