---
name: DevSkim

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 22 21 * * 5

permissions: read-all

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
        with:
          ignore-globs: "**/*.min.js,**/*.min.css,**/vendor/**,**/node_modules/**"

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: devskim-results.sarif
